console.log('importing scripts ...')

document.write(''
  +importJS('ElementalTypes', 'DataCollections/')
  +importJS('Rarity', 'DataCollections/')
  +importJS('Settings', 'DataCollections/')
  +importJS('CanvasManager', 'Manager/')
  +importJS('List', 'Base/')
  +importJS('Vector2', 'Base/')
  +importJS('EventManager','Manager/')
  +importJS('InputManager', 'Manager/')
  +importJS('RunManager', 'Manager/')
  +importJS('Utility', 'Utility/')
  +importJS('Paint', 'Utility/')
  +importJS('AudioPlayer', 'Utility/')
  +importJS('Component', 'Components/')
  +importJS('ProgressBarComponent', 'Components/GUI/')
  +importJS('InputRecieverComponent', 'Components/GUI/')
  +importJS('Scene', 'Scenes/')
  +importJS('BlankComponent', 'Components/')
  +importJS('DimensionComponent', 'Components/')
  +importJS('SizedComponent', 'Components/Rendering/')
  +importJS('CircleRenderComponent', 'Components/Rendering/') 
  +importJS('RectangleRenderComponent', 'Components/Rendering/') 
  +importJS('CollisionComponent', 'Components/Entity/') 
  +importJS('DeathTimerComponent', 'Components/Entity/') 
  +importJS('ParticleComponent', 'Components/Rendering/') 
  +importJS('ParticleSystemComponent', 'Components/Rendering/') 
  +importJS('DragComponent', 'Components/GUI/')
  +importJS('ClickComponent', 'Components/GUI/')
  +importJS('RisingTextComponent', 'Components/GUI/')
  +importJS('SpriteComponent', 'Components/Rendering/')
  +importJS('ExecutionTypes', 'DataCollections/')
  +importJS('SpellTriggerTypes', 'DataCollections/')
  +importJS('MoveComponent', 'Components/Entity/')
  +importJS('FPSCooldownComponent', 'Components/Entity/')
  
  +importJS('SpellChargeComponent', 'Components/Spells/')
  +importJS('SpellChannelComponent', 'Components/Spells/')
  +importJS('SpellRechargeComponent', 'Components/Spells/')
  +importJS('SpellComponent','Components/Spells/')
  +importJS('SpellOrbitComponent','Components/Spells/')
  +importJS('SpellStackComponent','Components/Spells/')
  +importJS('SpellGravityComponent','Components/Spells/')
  +importJS('SpellAttachComponent','Components/Spells/')
  +importJS('SpellDurationComponent','Components/Spells/')
  +importJS('SpellStunComponent', 'Components/Spells/')
  +importJS('SpellBlindComponent','Components/Spells/')
  +importJS('SpellDrainComponent','Components/Spells/')
  +importJS('TravelComponent','Components/Spells/')
  +importJS('SpellRepeatComponent','Components/Spells/')
  
  +importJS('AttributeModifierTypes', 'DataCollections/')
  +importJS('Attribute', 'Attribute/')
  +importJS('AttributeModifier', 'Attribute/')
  +importJS('AttributeModifierCollector', 'Attribute/')
  +importJS('AttributeSheet', 'Attribute/')
  +importJS('AttributePool', 'Attribute/')
  +importJS('ModifierFactory', 'Attribute/')
  +importJS('ItemList', 'Item/')
  +importJS('EquipmentComponent', 'Components/Entity/')
  +importJS('InventoryComponent', 'Components/Entity/')
  +importJS('RangeIndicatorComponent','Components/Entity/')
  +importJS('ModuleButtonComponent','Components/GUI/')


  +importJS('GameObject', 'Base/')
  +importJS('SceneryObject', 'LevelGeneration/')
  +importJS('SceneryClusterGenerator', 'LevelGeneration/')
  +importJS('GeneratorScene', 'LevelGeneration/')
  +importJS('TargetMarker', '')
  +importJS('Entity', 'Entity/')
  +importJS('EntityFinder', 'Entity/')
  +importJS('SpellEntity', 'Entity/')
  +importJS('EnemieEntity', 'Entity/')
  +importJS('EnemieBlueprint', 'Entity/')
  +importJS('FollowBehaviourComponent', 'Entity/EnemieBehaviour/')
  +importJS('RangedCasterFollowBehaviour', 'Entity/EnemieBehaviour/')
  +importJS('EnemieTypes', 'DataCollections/')
  +importJS('Item', 'Item/')
  +importJS('SpellCoreItem', 'Item/')
  +importJS('NodeItem', 'Item/')
  +importJS('SpellModuleItem', 'Item/')

  +importJS('TextRenderComponent', 'Components/Rendering/')
  +importJS('TextButton', 'GUI/')
  +importJS('TextBlock', 'GUI/')
  +importJS('TextBook', 'GUI/')
  +importJS('ItemInfoCardGUI', 'Item/')
  +importJS('ScrollPanel', 'GUI/')
  +importJS('ItemSlot', 'Item/')
  +importJS('ItemSlotPage', 'Item/')
  +importJS('PlayerController', 'GUI/')
  +importJS('InventoryButton', 'Components/GUI/')
  +importJS('CastWheelComponent','Components/GUI/')
  +importJS('EquipWheelComponent','Components/GUI/')
  +importJS('Player', 'Entity/')
  
  +importJS('World', 'LevelGeneration/Map/')
  +importJS('Maze', 'LevelGeneration/Map/')
  +importJS('CellDisplayComponent', 'LevelGeneration/Map/')
  
  +importJS('PassiveTreeDisplayScene', 'Scenes/')
  +importJS('PassiveTree', 'PassiveTree/')
  +importJS('NodeButton', 'PassiveTree/')
  +importJS('NodeInfo', 'PassiveTree/')
  +importJS('NodeTypes', 'DataCollections/')
  +importJS('NodeSelectionScene', 'Scenes/')
  +importJS('CharacterAttributeDisplayScene', 'Scenes/')

  +importJS('SceneBluePrint', 'Scenes/')
  +importJS('MainMenuScene', 'Scenes/')
  +importJS('TutorialScene', 'Scenes/')
  +importJS('PlayerScene', 'Scenes/')
  +importJS('InventoryScene', 'Scenes/')
  +importJS('InventoryItemDisplayScene', 'Scenes/')
  +importJS('ModuleInfoScene', 'Scenes/')
  +importJS('SpellCoreDisplayScene', 'Scenes/')
  +importJS('EquipmentScene', 'Scenes/')
  +importJS('SpellAttributeDisplayScene', 'Scenes/')
  +importJS('WorldScene', 'Scenes/')
  +importJS('SceneManager', 'Manager/')
  +importJS('GameManager', 'Manager/')
  +importJS('ImageLoader', 'Utility/')
  +importJS('PixelFont', 'Utility/')
  
  +importJS('Module', 'SpellModules/')
  +importJS('ModuleManager', 'SpellModules/')
  
  +importJS('TemporaryAttributeModule', 'SpellModules/AttributeModules/')
  +importJS('AttributeModule', 'SpellModules/AttributeModules/')
  +importJS('AreaModule', 'SpellModules/AttributeModules/')
  +importJS('CastSpeedModule', 'SpellModules/AttributeModules/')
  +importJS('CooldownModule', 'SpellModules/AttributeModules/')
  +importJS('CriticalModule', 'SpellModules/AttributeModules/')
  +importJS('EfficencyModule', 'SpellModules/AttributeModules/')
  +importJS('ElementalDamageModule', 'SpellModules/AttributeModules/')
  +importJS('ElementalResistanceModule', 'SpellModules/AttributeModules/')
  +importJS('TravelerModule', 'SpellModules/AttributeModules/')
  
  +importJS('BurstModule', 'SpellModules/CastModules/')
  +importJS('ChannelModule', 'SpellModules/CastModules/')
  +importJS('ChargeModule', 'SpellModules/CastModules/')
  +importJS('RepeatModule', 'SpellModules/CastModules/')
  
  +importJS('LifeModule', 'SpellModules/LifeModules/')
  +importJS('HealModule', 'SpellModules/LifeModules/')
  +importJS('LifeRechargeModule', 'SpellModules/LifeModules/')
  +importJS('DrainModule', 'SpellModules/LifeModules/')
  +importJS('ReserveModule', 'SpellModules/LifeModules/')
  
  +importJS('AttachModule', 'SpellModules/TravelModules/')
  +importJS('ChainModule', 'SpellModules/TravelModules/')
  +importJS('ForkModule', 'SpellModules/TravelModules/')
  +importJS('HomingModule', 'SpellModules/TravelModules/')
  +importJS('OrbitModule', 'SpellModules/TravelModules/')
  +importJS('PhysicalModule', 'SpellModules/TravelModules/')
  
  +importJS('BlindModule', 'SpellModules/SpecialModules/')
  +importJS('DurationModule', 'SpellModules/SpecialModules/')
  +importJS('GravityModule', 'SpellModules/SpecialModules/')
  +importJS('LeechModule', 'SpellModules/SpecialModules/')
  +importJS('RandomModule', 'SpellModules/SpecialModules/')
  +importJS('StackModule', 'SpellModules/SpecialModules/')
  +importJS('StunModule', 'SpellModules/SpecialModules/')
  
  +importJS('TriggerModule', 'SpellModules/TriggerModules/')
  +importJS('CastOnCriticalStrikeModule', 'SpellModules/TriggerModules/')
  +importJS('CastOnDamageTakenModule', 'SpellModules/TriggerModules/')
  +importJS('CastOnDeathModule', 'SpellModules/TriggerModules/')
  +importJS('CastOnHitModule', 'SpellModules/TriggerModules/')
  +importJS('CastOnKillModule', 'SpellModules/TriggerModules/')
  +importJS('MineModule', 'SpellModules/TriggerModules/')
  +importJS('TrapModule', 'SpellModules/TriggerModules/')
  
  +importJS('ModuleNameCollection', 'DataCollections/')
)


function importJS(name, path)
{
  console.log('importing: ' + name)
  return '<script src="./Scripts/' + path + name + '.js"></script>'
}

console.log('importing completed...')